### ISSUE TITLE
Improve asWKT property

### ISSUE THREAD

**Issue by rorlic** [Informatievlaanderen/VSDS-LDESWorkbench-NiFi#27]
Rename `Add 'asWKT' property` to `Add 'geo:asWKT' property`.
Use `geo:` instead of `geosparql:` as the prefix.
See https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_namespaces

**Comment by Yalz** [comment]
this seems incorrect: http://www.opengis.net/ont/geo#asWKT does not refer to a property. http://www.opengis.net/ont/geosparql#asWKT does.

**Comment by rorlic** [comment]
Closing the issue as the prefix is auto generated by Jena and the end result is the same (it is just a prefix).
