### ISSUE TITLE
Unable to get members from the IoW WaterQualityObserved LDES

### ISSUE THREAD

**Issue by ddvlanck** [Informatievlaanderen/VSDS-LDESWorkbench-NiFi#31]
In Apache Nifi, the LDES Client is configured to fetch LDES members from the IoW WaterQualityObserved LDES:
- Data source URL: `https://iow.smartdataspace.beta-vlaanderen.be/water-quality-observations-timebased`
- Data source format: `TURTLE`
- Data destination format: `n-quads`
- Fragment expiration interval: `30`

Tried the same with a more specific URL: `https://iow.smartdataspace.beta-vlaanderen.be/water-quality-observations-timebased?generatedAtTime=2022-10-26T12:46:23.772Z`. In this case, I also checked the logs from the Apache Nifi docker container and saw the following line:
`PROCESSED fragment https://iow.smartdataspace.beta-vlaanderen.be/water-quality-observations-timebased?generatedAtTime=2022-10-26T12:46:23.772Z (MUTABLE) has 0 member(s) and 0 tree:relation(s)`

**Comment by Yalz** [comment]
Issue has been retested with parameters and is resolved.
Feel free to reopen this ticket if the issue persists
