### ISSUE TITLE
Invalid processor type

### ISSUE THREAD

**Issue by zargha** [Informatievlaanderen/VSDS-LDESWorkbench-NiFi#75]
While building a docker image for ldes-workbench-nifi on git commit: [3f5d841d8afb85499c187bd3852d066d0c44998e](https://github.com/Informatievlaanderen/VSDS-LDESWorkbench-NiFi/commit/3f5d841d8afb85499c187bd3852d066d0c44998e), and then running, it was noted that when uploaded a [nifi-workflow.json](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/e2e-test/use-cases/gipod/1.replicate-ldes/nifi-workflow.json), the following error has been seen:

![error](https://user-images.githubusercontent.com/63961369/212689883-ba7dbd89-5ca4-4c16-be4f-05ee56236673.png)

**Comment by Tomvbe** [comment]
@zargha Can you check if this is still a problem when you use the most recent commit on the main branch? Everything should be working now

**Comment by xdxxxdx** [comment]
Hello @Tomvbe ,

I tried the issue on the commit:  [aa3a564526f238993838c8e2a799b6e3cac2f742](https://github.com/Informatievlaanderen/VSDS-LDESWorkbench-NiFi/commit/aa3a564526f238993838c8e2a799b6e3cac2f742)

(The tag provided by @rorlic for sprint 19, 31Jan - 14 Feb)
This issue stays. 

Regards
Xueying

**Comment by xdxxxdx** [comment]
Same issue stay for [3e78bf003409cf40247b9ab8944a52dd9742c675](https://github.com/Informatievlaanderen/VSDS-LDESWorkbench-NiFi/commit/3e78bf003409cf40247b9ab8944a52dd9742c675)
(The tag provided for sprint 20, 14Feb - 28 Feb)
This issue stays.
Please feel free to ping me if you need any other info.

**Comment by xdxxxdx** [comment]
Local build needs manually copy the Nar files to the /lib. As mentioned: 
https://vlaamseoverheid.atlassian.net/wiki/spaces/VSDSPUB/pages/6206390511/TC+UAT+NIFI+CLIENT+PROCESSOR+003+S+015
This issue is not valid.

**Comment by xdxxxdx** [comment]
Please feel free to close it.
