### ISSUE TITLE
Docker image ghcr.io/informatievlaanderen/nifi missing

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESWorkbench-NiFi#85]
Hello VSDS team,

I am following the demo: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/use-cases/gtfs-and-rt/5.including-stops

**Scenario:** 
Run `docker compose --env-file user.env up
`
**Current result:**
Error response from daemon: Head "https://ghcr.io/v2/informatievlaanderen/nifi/manifests/1.17.0-jdk17": denied

- If I run:  `docker pull ghcr.io/informatievlaanderen/nifi:1.17.0-jdk17` => same error.

- Browse: ghcr.io/informatievlaanderen/nifi => 404 error

I guess this image is deleted somehow? 
Please feel free to correct me if I am wrong.

Thanks 
XD

**Comment by rorlic** [comment]
@xdxxxdx as a workaround I have [updated the E2E repo](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/pull/151) to use the [original NiFi](https://hub.docker.com/r/apache/nifi) instead of this one (which has been [moved to docker hub](https://hub.docker.com/r/ldes/nifi/tags))

**Comment by xdxxxdx** [comment]
Validate on the : 
https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/commit/9c3c01ca4e1e8ecb97343e70892b70474f5ec549
